### ISSUE TITLE
Depends on wxpython?

### ISSUE THREAD

**Issue by TheChymera** [schollii/pypubsub#17]
As far back as `3.3.0` I notice imports like `import wx`? This doesn't sound right. I am in fact packaging your software in order to satisfy the dependencies of the newer wxpython versions. Are you aware of this circular dependency?

**Comment by schollii** [comment]
There is no circular dependency: the import wx is in the examples folder, maybe a couple places in the docs as example of use, they are meant for people who want to test/demo/sample with wx (since that is where pypubsub originated, there is a community of users there). There may be a dynamic introspection to determine if the 3.3.0 is being run from wx. If wx is installed, some special code is used. But there is no dependency on wx: if wx is present, pypubsub starts a little differently (in that release). 

For the latest wxPython, please do NOT install 3.3. I no longer maintain 3.3, it was overly complicated due to compatibility constraints on the old wxPython. What exactly are you trying to do?

**Comment by TheChymera** [comment]
I want to provide wxpython 4.0.3 for both python2.7 and 3.{4,5,6}. As I understand, for as long as I want to support python 2.7 I will have to depend on pypubsub 3.3.0

**Comment by schollii** [comment]
Indeed. My point is you shouldn't slow down the future to support the past. Support both by import pypubsub33 vs pypubsub4, or something like that. I'm going to close this as I don't see this as being a pypubsub issue, it is a wxPython integration issue, but please don't hesitate to re-open or post on dev forum to discuss further. Thanks!
